const providers = [
  {
    id: "plumb-01",
    name: "Mashauri Plumbing",
    category: "Plumbing",
    location: "Ruaka",
    description: "Leaks, sink installs, emergency repairs",
    priceFrom: 500,
    verified: true,
    availability: "today",
    responseTime: "10–30 mins",
    whatsapp: "254700000001",
    tags: ["leak", "sink", "toilet", "tap", "pipe", "plumber"],
  },
  {
    id: "clean-01",
    name: "Sparkle Homes",
    category: "Cleaning",
    location: "Ruaka / Two Rivers",
    description: "Deep cleaning, sofa cleaning, moving cleanup",
    priceFrom: 1500,
    verified: true,
    availability: "today",
    responseTime: "1 hour",
    whatsapp: "254700000002",
    tags: ["house", "sofa", "carpet", "cleaner", "maid"],
  },
  {
    id: "elec-01",
    name: "PowerFix Electricians",
    category: "Electrical",
    location: "Ruaka Highrise",
    description: "Wiring, socket repair, lighting installation",
    priceFrom: 800,
    verified: false,
    availability: "booking",
    responseTime: "2 hours",
    whatsapp: "254700000003",
    tags: ["lights", "sockets", "wiring", "electrician", "power"],
  },
  {
    id: "beauty-01",
    name: "Glamour Nails & Hair",
    category: "Beauty & Grooming",
    location: "Ruaka Town",
    description: "Manicure, pedicure, braiding, styling",
    priceFrom: 1000,
    verified: true,
    availability: "today",
    responseTime: "Instant",
    whatsapp: "254700000004",
    tags: ["nails", "hair", "salon", "braids", "beauty"],
  },
  {
    id: "tech-01",
    name: "Ruaka PC Medics",
    category: "IT & Tech",
    location: "Joyland",
    description: "Laptop repair, windows installation, wifi setup",
    priceFrom: 1000,
    verified: true,
    availability: "today",
    responseTime: "30 mins",
    whatsapp: "254700000005",
    tags: ["computer", "laptop", "internet", "wifi", "repair"],
  },
  {
    id: "tutor-01",
    name: "Teacher Sarah",
    category: "Tutoring",
    location: "Runda / Ruaka",
    description: "Maths & English tutoring for primary kids",
    priceFrom: 800,
    verified: false,
    availability: "booking",
    responseTime: "4 hours",
    whatsapp: "254700000006",
    tags: ["math", "english", "school", "tuition", "teacher"],
  },
  {
    id: "move-01",
    name: "Swift Movers",
    category: "Moving",
    location: "Ruaka",
    description: "House moving, pickup truck hire",
    priceFrom: 3000,
    verified: true,
    availability: "today",
    responseTime: "15 mins",
    whatsapp: "254700000007",
    tags: ["transport", "lorry", "pickup", "relocation", "mover"],
  },
  {
    id: "laundry-01",
    name: "Mama Fua Express",
    category: "Laundry",
    location: "Ruaka",
    description: "Hand wash, ironing, duvet cleaning",
    priceFrom: 500,
    verified: false,
    availability: "today",
    responseTime: "1 hour",
    whatsapp: "254700000008",
    tags: ["clothes", "wash", "ironing", "duvet"],
  },
  {
    id: "paint-01",
    name: "ColorPro Painters",
    category: "Painting",
    location: "Kiambu Road",
    description: "Interior wall painting and touchups",
    priceFrom: 2500,
    verified: false,
    availability: "booking",
    responseTime: "1 day",
    whatsapp: "254700000009",
    tags: ["walls", "paint", "renovation", "decor"],
  },
  {
    id: "beauty-02",
    name: "Fresh Fade Barbers",
    category: "Beauty & Grooming",
    location: "Delta",
    description: "House call barber services",
    priceFrom: 600,
    verified: true,
    availability: "today",
    responseTime: "10 mins",
    whatsapp: "254700000010",
    tags: ["haircut", "shave", "barber", "grooming"],
  },
  {
    id: "plumb-02",
    name: "QuickFix Handy",
    category: "Plumbing",
    location: "Ruaka",
    description: "General household repairs and plumbing",
    priceFrom: 400,
    verified: false,
    availability: "booking",
    responseTime: "3 hours",
    whatsapp: "254700000011",
    tags: ["repair", "fix", "handyman"],
  },
  {
    id: "clean-02",
    name: "Spotless Car Wash",
    category: "Cleaning",
    location: "Bypass",
    description: "Mobile car wash service",
    priceFrom: 300,
    verified: false,
    availability: "today",
    responseTime: "Instant",
    whatsapp: "254700000012",
    tags: ["car", "wash", "vehicle", "cleaning"],
  },
];
